- name: VM Deployment
  hosts: proxmox
  remote_user: root
  roles:
    - role: vm_deployment

- name: Samba config
  hosts: samba
  remote_user: root
  roles:
    - role: samba_setup

- name: Portainer config
  hosts: portainer
  become: true
  gather_facts: true
  roles:
    - role: portainer_setup
