- name: VM Deployment
  hosts: proxmox
  remote_user: root
  roles:
    - role: vm_deployment

- name: Samba config
  hosts: samba
  remote_user: root
  vars:
    ansible_ssh_common_args: -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
    host_key_checking: false
  roles:
    - role: samba_setup

- name: Portainer config
  hosts: portainer
  become: true
  gather_facts: true
  vars:
    ansible_ssh_common_args: -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
    host_key_checking: false
  roles:
    - role: portainer_setup
