---
- name: Proxmox config
  hosts: proxmox
  remote_user: root
  # Ignoring host-key trust prompt
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  vars_files:
    - vars/default.yml
  roles:
    - role: proxmox_setup
#     # - role: haos_setup

- name: Samba config
  hosts: samba
  remote_user: root
  # Ignoring host-key trust prompt
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  vars_files:
    - vars/default.yml
  roles:
    - role: samba_setup

- name: Portainer config
  hosts: portainer
  become: true
  gather_facts: false
  vars:
# Ignoring host-key trust prompt
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  vars_files:
    - vars/default.yml
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: portainer_setup
