---
- name: Main play
  hosts: portainer
  remote_user: root
  vars_files:
    - vars/default.yml
  roles:
    # - role: geerlingguy.pip
    # - role: geerlingguy.docker
    # - role: portainer_setup
    # - role: proxmox_setup
    - role: portainer_vm_deployment
