---
- name: Include portainer secrets variables
  ansible.builtin.include_vars:
    file: secret.portainer_installation.yml

- name: Portainer takes a moment to start, waiting
  ansible.builtin.wait_for:
    port: "{{ portainer_port }}"
    delay: 5

- name: Create portainer admin user
  ansible.builtin.uri:
    url: "https://{{ portainer_ip }}:{{ portainer_port }}/api/users/admin/init"
    method: POST
    body_format: json
    status_code: 200, 409
    validate_certs: false
    body:
      Username: "{{ portainer_username }}"
      Password: "{{ portainer_password }}"
