---
- name: Include portainer secrets variables
  ansible.builtin.include_vars:
    file: secret.portainer_installation.yml

# TODO: Refactor so token gets pulled only when it's absent
- name: Get a token if needed
  ansible.builtin.uri:
    url: "https://{{ portainer_ip }}:{{ portainer_port }}/api/auth"
    method: POST
    return_content: true
    body_format: json
    status_code: 200
    validate_certs: false
    body:
      Username: "{{ portainer_username }}"
      Password: "{{ portainer_password }}"
  register: auth_token

- name: Check if needed endpoint exists
  ansible.builtin.uri:
    url: "https://{{ portainer_ip }}:{{ portainer_port }}/api/endpoints/{{ portainer_endpoint_id }}"
    method: GET
    body_format: json
    status_code: 200, 404
    validate_certs: false
    headers:
      Authorization: Bearer {{ (auth_token.content | from_json).jwt }}
  register: endpoint_exists

- name: Create production endpoint
  ansible.builtin.uri:
    url: "https://{{ portainer_ip }}:{{ portainer_port }}/api/endpoints"
    method: POST
    body_format: form-multipart
    validate_certs: false
    headers:
      Authorization: Bearer {{ (auth_token.content | from_json).jwt }}
    body:
      Name: 'production'
      EndpointCreationType: '1'
      GroupID: '1'
  when: endpoint_exists.status == 404