- name: Check if portainer already exists
  community.docker.docker_container_info:
    name: portainer
  register: container
  check_mode: false

- name: Check if EE license key is provided and change edition if not
  ansible.builtin.set_fact:
    portainer_edition: ce
  when: portainer_license is not defined
  check_mode: false

- name: Template a docker-compose file
  ansible.builtin.template:
    src: compose/portainer.j2
    dest: /tmp/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  when: not container.exists

- name: Install portainer trough docker-compose
  community.docker.docker_compose_v2:
    project_src: "/tmp"
    project_name: portainer
  when: not container.exists

- name: Portainer takes a moment to start, waiting
  ansible.builtin.wait_for:
    port: "9443"
    delay: 5
  when: not container.exists
