- name: Configure the portainer
  ansible.builtin.include_tasks: installation.yml

- name: Configure the root user
  ansible.builtin.include_tasks: create_user.yml

- name: Install EE license
  ansible.builtin.include_tasks: install_license.yml

- name: Deploy all stacks
  ansible.builtin.include_tasks: deploy_stacks.yml

- name: Copy config files for stacks
  ansible.builtin.include_tasks: populate_configs.yml
