- name: Complete prerequisits
  ansible.builtin.include_tasks: prerequisite.yml

- name: Create required docker networks and volumes and populate them
  ansible.builtin.include_tasks: configure_docker.yml

- name: Install Portainer
  ansible.builtin.include_tasks: installation.yml

- name: Configure Portainer installation
  ansible.builtin.include_tasks: configure_portainer.yml

- name: Deploy all stacks
  ansible.builtin.include_tasks: deploy_stacks.yml
