- name: Check if pip is installed
  ansible.builtin.command: pip --version
  register: pip_version
  ignore_errors: true  # Ignore errors to handle the case where pip is not installed
  changed_when: pip_version != 0

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_version
  ignore_errors: true  # Ignore errors to handle the case where Docker is not installed
  changed_when: pip_version != 0

- name: Install pip if missing
  ansible.builtin.include_role:
    name: geerlingguy.pip
  when: pip_version.rc != 0

- name: Install Docker if missing
  ansible.builtin.include_role:
    name: geerlingguy.docker
  when: docker_version.rc != 0
