proxmox_ip: "{{ inventory_hostname }}"
proxmox_node: pve01test

cloud_init_vm_name: ubuntu-cloud

cloud_init_vm_id: "700"
portainer_vm_id: "200"

portainer_gateway: "192.168.31.1"
portainer_ip_changeto: "10.0.2.16"
