---
- name: Add No Subscription Repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
    filename: pve-no-subscription
    state: present

- name: Ensure enterprise repo file is not present
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Modify line in file to remove nag message
  replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: 'res[\s\n]*\.data\.status\.toLowerCase\(\) !== .active.'
    replace: "false"
    backup: yes
  notify: restart pveproxy