- name: Fetch Proxmox authentication token
  ansible.builtin.uri:
    url: "https://{{ proxmox_ip }}:8006/api2/json/access/ticket"
    method: POST
    return_content: true
    body_format: form-urlencoded
    status_code: 200
    validate_certs: false
    body:
      username: "{{ proxmox_username }}"
      password: "{{ proxmox_password }}"
  register: proxmox_ticket
  check_mode: false

- name: Proxmox configuration
  ansible.builtin.include_tasks: prerequisite.yml

- name: Create a cloud-init VM template
  ansible.builtin.include_tasks: cloud_init_deploy.yml

- name: Deploy Samba file share
  ansible.builtin.include_tasks: samba_lxc_deploy.yml

- name: Deploy Home-Assistant VM
  ansible.builtin.include_tasks: home_assistant_vm_deploy.yml

- name: Deploy a Portainer VM
  ansible.builtin.include_tasks: portainer_deploy.yml
