portainer_stack_list:
  adguardhome:
    TLS: true
  authelia:
  cloudflared:
  code-server:
  grafana:
    TLS: true
  homeassistant:
    TLS: true
  influxdb:
    TLS: true
  openbooks:
  traefik:
  watchtower:

portainer_edition: ee
portainer_ip: "{{ inventory_hostname }}"
portainer_port: 9493
portainer_endpoint_id: "1"
pip_install_packages:
 - name: docker-compose
