portainer_stack_list:
  - Container: adguardhome
    TLS: true
  - Container: authelia
  - Container: cloudflared
  - Container: code-server
  - Container: grafana
    TLS: true
  - Container: influxdb
    TLS: true
  - Container: openbooks
  - Container: traefik
  - Container: watchtower

portainer_edition: ee
portainer_ip: "{{ inventory_hostname }}"
portainer_port: 9493
portainer_endpoint_id: "1"
pip_install_packages:
 - name: docker-compose
