---
# - name: Removes subscription nag box
#   ansible.builtin.include_tasks: initial_setup.yml

- name: Create and install certificate
  ansible.builtin.include_tasks: ssl_setup.yml

# - name: Create an Ubuntu cloud-init template
#   ansible.builtin.include_tasks: cloud_init_vm_setup.yml
